### PR TITLE
Regenerate with svd2rust 0.17.0

### PR DESCRIPTION
**Pull request by jonas-schievink**
It looks like Nordic added more things to the SVD since the last version of this crate was generated?

Also adds readme instructions and updates the repo link.

Looks like the version was already bumped in the manifest, so a new release can probably be published immediately after this?

### CODE REVIEW

**Comment by thejpster** [comment]
Looks OK to me after a brief look-over. Thanks!

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Do we have bors?

**Comment by jonas-schievink** [comment]
Looks like there's no CI on any of the PACs

**Pull request merged**
