### PR TITLE
Updated to use thumbv8m capable cortex-m

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Comment by thejpster** [comment]
Any chance you could merge this? Or would you be able to grant me write access to crates.io/crates/nrf91 so I can push out an update?

**Comment by FrozenDroid** [comment]
Would really like to see this merged... @themadinventor

**Comment by themadinventor** [comment]
Oops, very sorry about that. I ended up not pursuing the Rust approach for the project I was working on, so I pretty much forgot about this repo. I'll look into sharing or transferring ownership :)

**Comment by thejpster** [comment]
Thank you!

**Pull request merged**
